"""init brief models

Revision ID: 14ea53d237a7
Revises: 
Create Date: 2026-06-21 15:39:30.611743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ea53d237a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['briefs.brief_id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['briefs.brief_id'], ),
    sa.PrimaryKeyConstraint('brief_id')
    )
    op.create_index(op.f('ix_briefs_assigned_to'), 'briefs', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_briefs_created_by'), 'briefs', ['created_by'], unique=False)
    op.create_index(op.f('ix_briefs_root_id'), 'briefs', ['root_id'], unique=False)
    op.create_table('brief_arbiter_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('brief_version', sa.Integer(), nullable=False),
    sa.Column('arbiter_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.brief_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_arbiter_reviews_brief_id'), 'brief_arbiter_reviews', ['brief_id'], unique=False)
    op.create_table('brief_chains',
    sa.Column('chain_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['briefs.brief_id'], ),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_table('brief_versions',
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('estimated_man_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_upstream_changed', sa.Boolean(), nullable=False),
    sa.Column('revision_reason', sa.String(length=255), nullable=False),
    sa.Column('modified_by', sa.Uuid(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.brief_id'], ),
    sa.PrimaryKeyConstraint('brief_id', 'version')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('brief_version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('from_user', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.brief_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_brief_id'), 'feedbacks', ['brief_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_from_user'), 'feedbacks', ['from_user'], unique=False)
    op.create_table('brief_transfer_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('brief_version', sa.Integer(), nullable=False),
    sa.Column('arbiter_review_id', sa.Uuid(), nullable=True),
    sa.Column('from_user', sa.Uuid(), nullable=False),
    sa.Column('to_user', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['arbiter_review_id'], ['brief_arbiter_reviews.id'], ),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.brief_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_transfer_history_brief_id'), 'brief_transfer_history', ['brief_id'], unique=False)
    op.create_index(op.f('ix_brief_transfer_history_from_user'), 'brief_transfer_history', ['from_user'], unique=False)
    op.create_index(op.f('ix_brief_transfer_history_to_user'), 'brief_transfer_history', ['to_user'], unique=False)
    op.create_table('feedback_arbiter_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('arbiter_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_arbiter_reviews_feedback_id'), 'feedback_arbiter_reviews', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_arbiter_reviews_feedback_id'), table_name='feedback_arbiter_reviews')
    op.drop_table('feedback_arbiter_reviews')
    op.drop_index(op.f('ix_brief_transfer_history_to_user'), table_name='brief_transfer_history')
    op.drop_index(op.f('ix_brief_transfer_history_from_user'), table_name='brief_transfer_history')
    op.drop_index(op.f('ix_brief_transfer_history_brief_id'), table_name='brief_transfer_history')
    op.drop_table('brief_transfer_history')
    op.drop_index(op.f('ix_feedbacks_from_user'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_brief_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_table('brief_versions')
    op.drop_table('brief_chains')
    op.drop_index(op.f('ix_brief_arbiter_reviews_brief_id'), table_name='brief_arbiter_reviews')
    op.drop_table('brief_arbiter_reviews')
    op.drop_index(op.f('ix_briefs_root_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_created_by'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_assigned_to'), table_name='briefs')
    op.drop_table('briefs')
    # ### end Alembic commands ###
