"""add modified_by_name to brief_versions

Revision ID: 20045ec299dd
Revises: cbaeb6ae983a
Create Date: 2026-06-27 22:48:59.790129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20045ec299dd'
down_revision: Union[str, Sequence[str], None] = 'cbaeb6ae983a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by_name', sa.String(length=255), nullable=True))

    # Backfill existing rows from the users table.
    op.execute("""
        UPDATE brief_versions
        SET modified_by_name = (
            SELECT users.name FROM users WHERE users.id = brief_versions.modified_by
        )
        WHERE modified_by_name IS NULL
    """)

    # Rows with no matching user get a fallback value.
    op.execute("""
        UPDATE brief_versions
        SET modified_by_name = 'Unknown'
        WHERE modified_by_name IS NULL
    """)

    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.alter_column('modified_by_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.drop_column('modified_by_name')
    # ### end Alembic commands ###
