"""add brief invites and drop email tokens

Revision ID: 42cbe8db781c
Revises: ad5d4d5da06c
Create Date: 2026-06-23 14:06:04.837480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42cbe8db781c'
down_revision: Union[str, Sequence[str], None] = 'ad5d4d5da06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brief_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('nonce', sa.String(length=24), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('temporary_user_id', sa.Uuid(), nullable=False),
    sa.Column('from_user', sa.Uuid(), nullable=False),
    sa.Column('final_user_id', sa.Uuid(), nullable=True),
    sa.Column('accept_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complete_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.brief_id'], ),
    sa.ForeignKeyConstraint(['final_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temporary_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_invites_brief_id'), 'brief_invites', ['brief_id'], unique=False)
    op.create_index(op.f('ix_brief_invites_final_user_id'), 'brief_invites', ['final_user_id'], unique=False)
    op.create_index(op.f('ix_brief_invites_from_user'), 'brief_invites', ['from_user'], unique=False)
    op.create_index(op.f('ix_brief_invites_nonce'), 'brief_invites', ['nonce'], unique=True)
    op.create_index(op.f('ix_brief_invites_temporary_user_id'), 'brief_invites', ['temporary_user_id'], unique=False)
    op.create_index(op.f('ix_brief_invites_token'), 'brief_invites', ['token'], unique=True)
    op.drop_index(op.f('ix_email_tokens_brief_id'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_email'), table_name='email_tokens')
    op.drop_table('email_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_temporary_user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(op.f('ix_users_from_temporary_user_id'), ['from_temporary_user_id'], unique=False)
        batch_op.create_foreign_key('fk_users_from_temporary_user_id', 'users', ['from_temporary_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_from_temporary_user_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_users_from_temporary_user_id'))
        batch_op.drop_column('from_temporary_user_id')
    op.create_table('email_tokens',
    sa.Column('token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('brief_id', sa.CHAR(length=32), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_email_tokens_email'), 'email_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_email_tokens_brief_id'), 'email_tokens', ['brief_id'], unique=False)
    op.drop_index(op.f('ix_brief_invites_token'), table_name='brief_invites')
    op.drop_index(op.f('ix_brief_invites_temporary_user_id'), table_name='brief_invites')
    op.drop_index(op.f('ix_brief_invites_nonce'), table_name='brief_invites')
    op.drop_index(op.f('ix_brief_invites_from_user'), table_name='brief_invites')
    op.drop_index(op.f('ix_brief_invites_final_user_id'), table_name='brief_invites')
    op.drop_index(op.f('ix_brief_invites_brief_id'), table_name='brief_invites')
    op.drop_table('brief_invites')
    # ### end Alembic commands ###
