"""add_brief_type_to_briefs_and_versions

Revision ID: 6a50f0011492
Revises: a23a9807994f
Create Date: 2026-07-08 00:14:13.116813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a50f0011492'
down_revision: Union[str, Sequence[str], None] = 'a23a9807994f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), server_default='idea', nullable=False))

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), server_default='idea', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
