"""add task_queue and extend brief_arbiter_reviews

Revision ID: 9dd38140350e
Revises: 6a50f0011492
Create Date: 2026-07-12 17:56:03.762864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Uuid


# revision identifiers, used by Alembic.
revision: str = '9dd38140350e'
down_revision: Union[str, Sequence[str], None] = '6a50f0011492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_queue',
    sa.Column('id', Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.create_index('idx_queue_fetch', ['created_at'], unique=False)

    with op.batch_alter_table('brief_arbiter_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=512), nullable=True))
        batch_op.alter_column('reviewed_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_arbiter_reviews', schema=None) as batch_op:
        batch_op.alter_column('reviewed_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('webhook_url')
        batch_op.drop_column('error')
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('attempt_count')

    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_queue_fetch')

    op.drop_table('task_queue')
    # ### end Alembic commands ###
