"""update_brief_dual_state_and_redundant_fields

Revision ID: b780f9fe0bcd
Revises: 42cbe8db781c
Create Date: 2026-06-27 18:16:25.804760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b780f9fe0bcd'
down_revision: Union[str, Sequence[str], None] = '42cbe8db781c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_chains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('owner_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=False))
        batch_op.create_index(batch_op.f('ix_brief_chains_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('brief_transfer_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('to_user_name', sa.String(length=255), nullable=False))

    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('expected_completion_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('arbiter_review_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_brief_versions_arbiter_review_id', 'brief_arbiter_reviews', ['arbiter_review_id'], ['id'])

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upstream_state', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('downstream_state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('expected_completion_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('created_by_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('assigned_to_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('status_changed_by', sa.Uuid(), nullable=False))
        batch_op.alter_column('current_version',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_to_down', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('from_user_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('to_user', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('to_user_name', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_feedbacks_to_user'), ['to_user'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_to_user'))
        batch_op.drop_column('to_user_name')
        batch_op.drop_column('to_user')
        batch_op.drop_column('from_user_name')
        batch_op.drop_column('is_to_down')

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('current_version',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status_changed_by')
        batch_op.drop_column('status_changed_at')
        batch_op.drop_column('assigned_to_name')
        batch_op.drop_column('created_by_name')
        batch_op.drop_column('expected_completion_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('title')
        batch_op.drop_column('downstream_state')
        batch_op.drop_column('upstream_state')

    with op.batch_alter_table('brief_versions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_brief_versions_arbiter_review_id', type_='foreignkey')
        batch_op.drop_column('arbiter_review_id')
        batch_op.drop_column('expected_completion_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('brief_transfer_history', schema=None) as batch_op:
        batch_op.drop_column('to_user_name')
        batch_op.drop_column('from_user_name')

    with op.batch_alter_table('brief_chains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brief_chains_owner_id'))
        batch_op.drop_column('priority')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
