"""add status_changed_by_name to briefs

Revision ID: cbaeb6ae983a
Revises: b780f9fe0bcd
Create Date: 2026-06-27 22:38:36.883635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbaeb6ae983a'
down_revision: Union[str, Sequence[str], None] = 'b780f9fe0bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_changed_by_name', sa.String(length=255), nullable=True))

    # Backfill existing rows from the users table.
    op.execute("""
        UPDATE briefs
        SET status_changed_by_name = (
            SELECT users.name FROM users WHERE users.id = briefs.status_changed_by
        )
        WHERE status_changed_by_name IS NULL
    """)

    # Rows with no matching user get a fallback value.
    op.execute("""
        UPDATE briefs
        SET status_changed_by_name = 'Unknown'
        WHERE status_changed_by_name IS NULL
    """)

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.alter_column('status_changed_by_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_column('status_changed_by_name')
    # ### end Alembic commands ###
